### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by jorisdral**
*Short description of your PR*

Checklist:
- [ ] run `fmt.sh` in the repo root directory

### CODE REVIEW

**Comment by jorisdral** [comment]
> I know what's wrong here, working on a fix right now

I tried using `quickcheck-dynamic` in a project with `ghc-9.6.2` but the compilation error arises that I had hoped to have fixed in https://github.com/input-output-hk/quickcheck-dynamic/pull/38. By adding `ghc926` to the supported compilers, we should be able to see the compilation failure in CI next time

**Comment by zeme-wana** [comment]
I will let you take care of the haskell compiler errors but there is also a nix failure that I'm addressing.
You mention both ghc962 and ghc926 in your comments, and this PR title mentions ghc961.
Which one exactly do we want to support in this PR?

**Comment by jorisdral** [comment]
> I will let you take care of the haskell compiler errors but there is also a nix failure that I'm addressing.
You mention both ghc962 and ghc926 in your comments, and this PR title mentions ghc961.
Which one exactly do we want to support in this PR?

Oops, my bad, I meant `ghc961`. I added `ghc961` to the list of supported compilers because I thought `ghc962` isn't supported by `iogx`. It isn't listed here: https://github.com/input-output-hk/iogx#321-supportedcompilers.

**Comment by zeme-wana** [comment]
Yes. I just added support for 962.
If you don't mind, we should close this PR and work on https://github.com/input-output-hk/quickcheck-dynamic/pull/50 instead. Let me take this over until the nix failures are gone and then you can deal with the haskell errors.

**Comment by jorisdral** [comment]
> Yes. I just added support for 962. If you don't mind, we should close this PR and work on https://github.com/input-output-hk/quickcheck-dynamic/pull/50 instead. Let me take this over until the nix failures are gone and then you can deal with the haskell errors.

I closed the PR. Just FYI (sorry if it's superfluous info): Cardano-related packages need to be able to build/test with `ghc-8.10.7` at the minimum (at least for now), and `ghc-9.2.8` and `ghc-9.6.2` are supported in most cases. Would it makes sense to run Hydra jobs for each of these compilers in `quickcheck-dynamic`?

**Pull request closed without merging**
