### PR TITLE
Compatibility with `ghc-9.4` and `ghc-9.6`

### PR DESCRIPTION
**Pull request by jorisdral**
This PR fixes some compilation errors that arise in `ghc-9.4` and `ghc-9.6`, making `quickcheck-dynamic` (almost) compatible with `ghc-9.4` and `ghc-9.6`. 

It seems that most of the errors were caused by interaction between the `OVERLAPPABLE` instance for `HasVariables` and the scoping of type variables where a `StateModel state` constraint is required by the context.  Example:

```sh
...
[6 of 9] Compiling Test.QuickCheck.StateModel ...

src/Test/QuickCheck/StateModel.hs:315:79: error:
    • Missing instance of HasVariables for non-Generic type Action
                                                              state1 a1
    • In the expression: computeShrinkAction s act
      In a stmt of a list comprehension:
        Some act' <- computeShrinkAction s act
      In the expression:
        [(unsafeCoerceVar v := act', s) |
           Some act' <- computeShrinkAction s act]
    |
315 |       shrinker (v := act, s) = [(unsafeCoerceVar v := act', s) | Some act' <- computeShrinkAction s act]
    |                                                                               ^^^^^^^^^^^^^^^^^^^
...
```
Using explicit type application to specify the `state` type variables prevents such an error:
```haskell
      shrinker (v := act, s) = [(unsafeCoerceVar v := act', s) | Some act' <- computeShrinkAction @state s act]
```

Yet to fix:
- [ ] The `cabal.project` file contains an `allow-newer` stanza for `text`, since `tasty-test-reporter` has a too strict bound on `text`. The version bounds should probably be relaxed in `tasty-test-reporter` itself.
- [ ] Since `io-classes-1.0.0.0`, `threadStatus` is remove from the `MonadFork` class. This means that the `Registry` test for `quickcheck-dynamic-iosim` fails to compile.

Checklist:
- [ ] run `fmt.sh` in the repo root directory

### CODE REVIEW

**Comment by MaximilianAlgehed** [comment]
I think this looks good. I'm glad you're pulling on this. Thank you!

Does the pinned version of io-sim that this PR removes from `cabal.project` compile with recent versions of ghc? I'm asking because that allows us to push fixing the registry example into the future.

@abailly-iohk do you have the chops to add builds for these ghc versions to the github workflows?

@zeme-iohk do you know what the status is on versions of ghc in other IOG repos? Would it be easy to bump the ghc version in the nix files? (perhaps you have something to say about the question posed to Arnaud above?)

**Comment by abailly-iohk** [comment]
@MaximilianAlgehed Sure, can do!

**Review by abailly-iohk — APPROVED** [review]

**Comment by jorisdral** [comment]
>Does the pinned version of io-sim that this PR removes from cabal.project compile with recent versions of ghc? I'm asking because that allows us to push fixing the registry example into the future.

For `ghc-9.4.5`, adding `allow-newer: text` to the `cabal.project` is sufficient to make the project compile. For `ghc-9.6.2` we need to relax upper bounds on `base` and this is not as straightforward because it causes compilation failures in other dependencies.

```
cabal build all --with-compiler=ghc-9.6.2 --minimize-conflict-set
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] next goal: io-classes (user goal)
[__0] rejecting: io-classes-1.1.0.0, io-classes-1.0.0.1, io-classes-1.0.0.0
(constraint from user target requires ==0.2.0.0)
[__0] trying: io-classes-0.2.0.0
[__1] next goal: base (dependency of io-classes)
[__1] rejecting: base-4.18.0.0/installed-4.18.0.0 (conflict: io-classes =>
base>=4.9 && <4.18)
[__1] skipping: base-4.18.0.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=4.9 && <4.18' from
'io-classes')
[__1] rejecting: base-4.17.1.0, base-4.17.0.0, base-4.16.4.0, base-4.16.3.0,
base-4.16.2.0, base-4.16.1.0, base-4.16.0.0, base-4.15.1.0, base-4.15.0.0,
base-4.14.3.0, base-4.14.2.0, base-4.14.1.0, base-4.14.0.0, base-4.13.0.0,
base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0, base-4.10.0.0,
base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0,
base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0,
base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0,
base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0,
base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from non-upgradeable
package requires installed instance)
[__1] fail (backjumping, conflict set: base, io-classes)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, io-classes
```

After adding this to `cabal.project`:

```
allow-newer:
  text,
  io-classes:base,
  io-sim:base

constraints:
  base < 4.19
  ```
  
  We now get:
  
  ```
 cabal build all --with-compiler=ghc-9.6.2 --minimize-conflict-set
Resolving dependencies...
Build profile: -w ghc-9.6.2 -O1
In order, the following will be built (use -v for more details):
 - deque-0.3 (lib) (requires build)
 - io-classes-0.2.0.0 (lib) (requires build)
 - io-sim-0.2.0.0 (lib) (requires build)
 - quickcheck-dynamic-iosim-0.1.0.0 (lib) (configuration changed)
 - quickcheck-dynamic-iosim-0.1.0.0 (test:quickcheck-dynamic-iosim-test) (configuration changed)
Starting     deque-0.3 (lib)
Building     deque-0.3 (lib)

Failed to build deque-0.3.
Build log (...):
Configuring library for deque-0.3..
Preprocessing library for deque-0.3..
Building library for deque-0.3..
[1 of 6] Compiling Deque.Prelude    ( library/Deque/Prelude.hs, dist/build/Deque/Prelude.o, dist/build/Deque/Prelude.dyn_o )
[2 of 6] Compiling Deque.Lazy       ( library/Deque/Lazy.hs, dist/build/Deque/Lazy.o, dist/build/Deque/Lazy.dyn_o )

library/Deque/Lazy.hs:207:3: error: [GHC-54721]
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
207 |   fail = const mempty
    |   ^^^^
[4 of 6] Compiling Deque.StrictList ( library/Deque/StrictList.hs, dist/build/Deque/StrictList.o, dist/build/Deque/StrictList.dyn_o )
[5 of 6] Compiling Deque.Strict     ( library/Deque/Strict.hs, dist/build/Deque/Strict.o, dist/build/Deque/Strict.dyn_o )

library/Deque/Strict.hs:219:3: error: [GHC-54721]
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
219 |   fail = const mempty
    |   ^^^^
Error: cabal: Failed to build deque-0.3 (which is required by
test:quickcheck-dynamic-iosim-test from quickcheck-dynamic-iosim-0.1.0.0). See
the build log above for details.
```

**Comment by MaximilianAlgehed** [comment]
FYI #42 fixes the issue with io-sim as far as I'm aware. So once that's merged I think we can go ahead with this.

**Review by MaximilianAlgehed — APPROVED** [review]

**Pull request merged**
