### PR TITLE
State-model compatibility layer to do IOSim models

### PR DESCRIPTION
**Pull request by MaximilianAlgehed**
We need to add stray `s` to the `ActionMonad` in order to be able to nicely build state models that run in `IOSim` or `ST`. However, in order to have models that have something interesting in their model state, e.g. a `Var (ThreadId s)` we would require the `s` to be typeable. To get around this we build a layer of indirection that hides the `s`.

This is a WIP PR, we still need to figure out:
1. What's the best, most elegant, way to implement this indirection (the current draft works but isn't pretty)
2. How are we going to deal with the dependency on `io-sim` that we've just introduced if we want to go to Hackage?

I don't have any great answers for 1, perhaps a re-work could make it nicer. For 2 I think there is only really one option considering we need this stuff down-stream and that's to either put only `io-classes` (and do a bit of a re-work of the compat layer) or all of `io-sim` on Hackage. I would favour putting all of `io-sim` on Hackage.

### CODE REVIEW

**Comment by abailly-iohk** [comment]
@MaximilianAlgehed I have pushed 2 changes:
1. One for splitting out the io-sim stuff to its own package
2. Another one for extracting a `RunModel` typeclass. This looks nicer in the `StateModel.hs` file but I could not make it work in the other package before the week-end.

**Comment by MaximilianAlgehed** [comment]
Super. I'll look into making it work today.

Best regards
*Maximilian Algehed*

**Comment by MaximilianAlgehed** [comment]
@abailly-iohk I suggest we merge this now so that the new version of `StateModel` is on `main` and we can clean up the `io-sim-compat` stuff later?

**Comment by abailly-iohk** [comment]
OK, I will make it green and then merge it

**Review by abailly-iohk — APPROVED** [review]

**Comment by MaximilianAlgehed** [comment]
Great.

**Pull request merged**
